// lib/dummy/master/patients.ts

import type { PatientData } from "@/lib/shared/types/patient"

export const MASTER_PATIENTS: PatientData[] = [
  {
    id: "1",
    nrm: "000001",
    nama: "Hana Qurratu A'yun",
    nik: "3302207705080003",
    tanggalLahir: "2007-05-08",
    tempatLahir: "Tegal",
    jenisKelamin: "P",
    golonganDarah: "O",
    statusNikah: "Belum Menikah",
    pekerjaan: "Pelajar",
    catatanKhusus: "-",
    alamat: "Jl. Mawar No. 1, Tegal",
    penanggungJawab: "Ayah",
    namaPJ: "Budi Santoso",
    pekerjaanPJ: "Wiraswasta",
    noTelpPJ: "08123456889",
    penjamin: "BPJS",
    nama_instansi: "BPJS Kesehatan",
    nomor_surat: "123456789",
    asalRujukan: "Puskesmas Tegal",
    noRujukan: "RUJ001",
    kunjunganTerakhir: "3 kali kunjungan",
    layananTerakhir: "Poli Umum",
    tanggalTerdaftar: "2023-02-10",
    status: "Aktif",
  },

  {
    id: "2",
    nrm: "000002",
    nama: "Muhammad Fadhlan",
    nik: "3302200408010004",
    tanggalLahir: "2001-08-04",
    tempatLahir: "Slawi",
    jenisKelamin: "L",
    golonganDarah: "A",
    statusNikah: "Belum Menikah",
    pekerjaan: "Mahasiswa",
    catatanKhusus: "-",
    alamat: "Jl. Kenanga, Slawi",
    penanggungJawab: "Ibu",
    namaPJ: "Siti Aminah",
    pekerjaanPJ: "Guru",
    noTelpPJ: "082233445566",
    penjamin: "Umum",
    tanggalTerdaftar: "2021-10-15",
    status: "Aktif",
  },
]
