// lib/dummy/master/patients.ts

import type { PatientData } from "@/lib/shared/types/patient"

export const MASTER_PATIENTS: PatientData[] = [
  {
    id: "1",
    nrm: "000001",
    nama: "Hana Qurratu A'yun",
    nik: "3302207705080003",
    tanggalLahir: "2007-05-08",
    tempatLahir: "Tegal",
    jenisKelamin: "P",
    golonganDarah: "O",
    statusNikah: "Belum Menikah",
    pekerjaan: "Pelajar",
    catatanKhusus: "-",
    alamat: "Jl. Mawar No. 1, Tegal",
    penanggungJawab: "Ayah",
    namaPJ: "Budi Santoso",
    pekerjaanPJ: "Wiraswasta",
    noTelpPJ: "08123456889",
    penjamin: "BPJS",
    nama_instansi: "BPJS Kesehatan",
    nomor_surat: "123456789",
    asalRujukan: "Puskesmas Tegal",
    noRujukan: "RUJ001",
    kunjunganTerakhir: "3 kali kunjungan",
    layananTerakhir: "Poli Umum",
    tanggalTerdaftar: "2023-02-10",
    status: "Aktif",
  },

  {
    id: "2",
    nrm: "000002",
    nama: "Muhammad Fadhlan",
    nik: "3302200408010004",
    tanggalLahir: "2001-08-04",
    tempatLahir: "Slawi",
    jenisKelamin: "L",
    golonganDarah: "A",
    statusNikah: "Belum Menikah",
    pekerjaan: "Mahasiswa",
    catatanKhusus: "-",
    alamat: "Jl. Kenanga, Slawi",
    penanggungJawab: "Ibu",
    namaPJ: "Siti Aminah",
    pekerjaanPJ: "Guru",
    noTelpPJ: "082233445566",
    penjamin: "Umum",
    tanggalTerdaftar: "2021-10-15",
    status: "Aktif",
  },

  {
    id: "3",
    nrm: "000003",
    nama: "Siti Nurhaliza",
    nik: "3302201505920005",
    tanggalLahir: "1992-05-15",
    tempatLahir: "Jakarta",
    jenisKelamin: "P",
    golonganDarah: "B",
    statusNikah: "Menikah",
    pekerjaan: "Pegawai Swasta",
    catatanKhusus: "-",
    alamat: "Jl. Merpati No. 5, Jakarta",
    penanggungJawab: "Suami",
    namaPJ: "Ahmad Yani",
    pekerjaanPJ: "Dokter",
    noTelpPJ: "081234567890",
    penjamin: "BPJS",
    nama_instansi: "BPJS Kesehatan",
    nomor_surat: "987654321",
    asalRujukan: "Puskesmas Jakarta",
    noRujukan: "RUJ002",
    tanggalTerdaftar: "2022-03-20",
    status: "Aktif",
  },

  {
    id: "4",
    nrm: "000004",
    nama: "Anjani Shatila",
    nik: "337401060990009",
    tanggalLahir: "1990-06-01",
    tempatLahir: "Depok",
    jenisKelamin: "P",
    golonganDarah: "O",
    statusNikah: "Menikah",
    pekerjaan: "Ibu Rumah Tangga",
    catatanKhusus: "-",
    alamat: "Jl Pengabdian RT 06 RW 03 No 13, Desa Apahyuo, Kecamatan Depok, Kabupaten Sleman, Jogjakarta 57234",
    penanggungJawab: "Suami",
    namaPJ: "Anjani Shatila",
    pekerjaanPJ: "Diri Sendiri",
    noTelpPJ: "085673456278",
    penjamin: "BPJS",
    nama_instansi: "BPJS Kesehatan",
    nomor_surat: "123456780123 / 123456789012J",
    asalRujukan: "Puskesmas Purwokerto Timur",
    noRujukan: "123456789012J",
    tanggalTerdaftar: "2017-06-25",
    status: "Aktif",
  },

  {
    id: "5",
    nrm: "000005",
    nama: "Dewi Sartika",
    nik: "3302201812950006",
    tanggalLahir: "1995-12-18",
    tempatLahir: "Bandung",
    jenisKelamin: "P",
    golonganDarah: "AB",
    statusNikah: "Belum Menikah",
    pekerjaan: "Guru",
    catatanKhusus: "-",
    alamat: "Jl. Anggrek No. 12, Bandung",
    penanggungJawab: "Ayah",
    namaPJ: "Supriyadi",
    pekerjaanPJ: "PNS",
    noTelpPJ: "082345678901",
    penjamin: "Umum",
    tanggalTerdaftar: "2023-01-15",
    status: "Aktif",
  },

  {
    id: "6",
    nrm: "000006",
    nama: "Dimas Pratama",
    nik: "3302202203980007",
    tanggalLahir: "1998-03-22",
    tempatLahir: "Semarang",
    jenisKelamin: "L",
    golonganDarah: "A",
    statusNikah: "Belum Menikah",
    pekerjaan: "Karyawan Swasta",
    catatanKhusus: "-",
    alamat: "Jl. Melati No. 8, Semarang",
    penanggungJawab: "Ibu",
    namaPJ: "Sri Utami",
    pekerjaanPJ: "Pedagang",
    noTelpPJ: "083456789012",
    penjamin: "BPJS",
    nama_instansi: "BPJS Kesehatan",
    nomor_surat: "456789012",
    asalRujukan: "Puskesmas Semarang",
    noRujukan: "RUJ003",
    tanggalTerdaftar: "2023-05-10",
    status: "Aktif",
  },
]

