import type { PatientVisit } from "@/lib/shared/types/visit"

function todayDate() {
  const now = new Date()
  return now.toISOString().slice(0, 10)
}

export const TODAY_PD_VISITS: PatientVisit[] = [
  {
    idPasien: "1",
    nrm: "000001",
    nama: "Ahmad Ramadhan",
    jenisKelamin: "L",

    noAntrian: "001",
    noRegistrasi: "PD-2025-001",
    tanggalKunjungan: todayDate(),

    poli: "penyakit-dalam",
    status: "completed",
  },
  {
    idPasien: "2",
    nrm: "000002",
    nama: "Muhammad Fadhlan",
    jenisKelamin: "L",

    noAntrian: "002",
    noRegistrasi: "PD-2025-002",
    tanggalKunjungan: todayDate(),

    poli: "penyakit-dalam",
    status: "completed",
  },
  {
    idPasien: "3",
    nrm: "000003",
    nama: "Siti Nurhaliza",
    jenisKelamin: "P",

    noAntrian: "003",
    noRegistrasi: "PD-2025-003",
    tanggalKunjungan: todayDate(),

    poli: "penyakit-dalam",
    status: "completed",
  },
  {
    idPasien: "4",
    nrm: "000004",
    nama: "Budi Santoso",
    jenisKelamin: "L",

    noAntrian: "004",
    noRegistrasi: "PD-2025-004",
    tanggalKunjungan: todayDate(),

    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "5",
    nrm: "000005",
    nama: "Dewi Sartika",
    jenisKelamin: "P",

    noAntrian: "005",
    noRegistrasi: "PD-2025-005",
    tanggalKunjungan: todayDate(),

    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "6",
    nrm: "000006",
    nama: "Dimas Pratama",
    jenisKelamin: "L",
    noAntrian: "006",
    noRegistrasi: "PD-2025-006",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "17",
    nrm: "000017",
    nama: "Rizky Amelia",
    jenisKelamin: "P",
    noAntrian: "007",
    noRegistrasi: "PD-2025-007",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "28",
    nrm: "000028",
    nama: "Fauzan Hidayat",
    jenisKelamin: "L",
    noAntrian: "008",
    noRegistrasi: "PD-2025-008",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "19",
    nrm: "000019",
    nama: "Aulia Putri",
    jenisKelamin: "P",
    noAntrian: "009",
    noRegistrasi: "PD-2025-009",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "120",
    nrm: "000120",
    nama: "Irwan Saputra",
    jenisKelamin: "L",
    noAntrian: "010",
    noRegistrasi: "PD-2025-010",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "21",
    nrm: "000021",
    nama: "Nabila Zahra",
    jenisKelamin: "P",
    noAntrian: "011",
    noRegistrasi: "PD-2025-011",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "22",
    nrm: "000022",
    nama: "Fikri Ramadhan",
    jenisKelamin: "L",
    noAntrian: "012",
    noRegistrasi: "PD-2025-012",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "23",
    nrm: "000023",
    nama: "Melani Wulandari",
    jenisKelamin: "P",
    noAntrian: "013",
    noRegistrasi: "PD-2025-013",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "24",
    nrm: "000024",
    nama: "Hafiz Jamal",
    jenisKelamin: "L",
    noAntrian: "014",
    noRegistrasi: "PD-2025-014",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
  {
    idPasien: "25",
    nrm: "000025",
    nama: "Sari Oktaviani",
    jenisKelamin: "P",
    noAntrian: "015",
    noRegistrasi: "PD-2025-015",
    tanggalKunjungan: todayDate(),
    poli: "penyakit-dalam",
    status: "waiting",
  },
]
