-- Create payment_codes table
CREATE TABLE IF NOT EXISTS payment_codes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  visit_id UUID NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
  code VARCHAR(12) UNIQUE NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  used_at TIMESTAMP,
  used_by UUID REFERENCES users(id),
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP DEFAULT (NOW() + INTERVAL '3 days')
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_payment_codes_code ON payment_codes(code);
CREATE INDEX IF NOT EXISTS idx_payment_codes_visit_id ON payment_codes(visit_id);
CREATE INDEX IF NOT EXISTS idx_payment_codes_is_used ON payment_codes(is_used);

-- Add comment
COMMENT ON TABLE payment_codes IS 'Stores unique payment codes generated by doctors for cashier verification';
COMMENT ON COLUMN payment_codes.code IS 'Unique payment code in format PAY-XXXXXXXX';
COMMENT ON COLUMN payment_codes.is_used IS 'Flag to track if code has been used for payment';
COMMENT ON COLUMN payment_codes.expires_at IS 'Code expiration timestamp (default 3 days from creation)';
