import type { PatientData } from "@/lib/shared/types"

export const PATIENTS_DATA: PatientData[] = [
  {
    id: "1",
    nrm: "000001",
    nama: "Hana Qurratu A'yun",
    nik: "3302207705080003",
    tanggalLahir: "2007-05-08",
    tempatLahir: "Tegal",
    jenisKelamin: "P",
    golonganDarah: "O",
    agama: "Islam",
    pendidikan: "SMA",
    alamat: "Jl. Mawar No. 1, Tegal",
    pekerjaan: "Pelajar",
    statusNikah: "Belum Menikah",
    penjamin: "BPJS",
    nama_instansi: "BPJS Kesehatan",
    nomor_surat: "123456789",
    noBPJS: "0987654321",
    kelasBPJS: "2",
    penanggungJawab: "Ayah",
    namaPJ: "Budi Santoso",
    pekerjaanPJ: "Wiraswasta",
    noTelpPJ: "08123456889",
    tanggalTerdaftar: "2023-02-10",
    status: "Aktif",
    asalRujukan: "Puskesmas Tegal",
    noRujukan: "RUJ001",
    kunjunganTerakhir: "3 kali",
    layananTerakhir: "Poli Umum",
  },
]
