import type { NextApiRequest, NextApiResponse } from 'next';
import { supabaseServer } from '@/lib/supabase/server';

/**
 * API Endpoint: Register Patient
 * 
 * New workflow with separated tables:
 * 1. Verify queue_ticket exists and is 'called'
 * 2. Validate poli and doctor quotas
 * 3. INSERT new visit record (not UPDATE)
 * 4. Update queue_ticket status to 'completed'
 */

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { 
      ticket_id,
      patient_id,
      poli_id,
      dokter_id,
      penjamin_id,
      keluhan,
      harga,
      kunjungan_ke
    } = req.body;

    // Validate required fields
    if (!ticket_id || !patient_id || !poli_id || !dokter_id) {
      return res.status(400).json({ 
        error: 'Missing required fields',
        required: ['ticket_id', 'patient_id', 'poli_id', 'dokter_id']
      });
    }

    // ============================================
    // Step 1: Verify queue ticket exists and is called
    // ============================================
    
    const { data: ticket, error: ticketError } = await supabaseServer
      .from('queue_tickets')
      .select('*')
      .eq('id', ticket_id)
      .single();

    if (ticketError || !ticket) {
      return res.status(404).json({ 
        error: 'Queue ticket not found' 
      });
    }

    if (ticket.status !== 'called') {
      return res.status(400).json({ 
        error: 'Invalid ticket status',
        message: 'Ticket must be in "called" status to register',
        current_status: ticket.status
      });
    }

    // ============================================
    // Step 2: Check poli quota
    // ============================================
    
    const { data: poliQuotaAvailable, error: poliQuotaError } = await supabaseServer
      .rpc('check_poli_quota', { p_poli_id: poli_id });

    if (poliQuotaError) {
      console.error('Error checking poli quota:', poliQuotaError);
      throw poliQuotaError;
    }

    if (!poliQuotaAvailable) {
      // Mark ticket as no_show (quota full)
      await supabaseServer
        .from('queue_tickets')
        .update({ status: 'no_show' })
        .eq('id', ticket_id);

      return res.status(400).json({ 
        error: 'Poli quota exceeded',
        message: 'Kuota poli untuk hari ini sudah penuh',
        quota_status: 'full'
      });
    }

    // ============================================
    // Step 3: Check doctor quota
    // ============================================
    
    const { data: doctorQuotaAvailable, error: doctorQuotaError } = await supabaseServer
      .rpc('check_doctor_quota', { p_dokter_id: dokter_id });

    if (doctorQuotaError) {
      console.error('Error checking doctor quota:', doctorQuotaError);
      throw doctorQuotaError;
    }

    if (!doctorQuotaAvailable) {
      // Mark ticket as no_show (quota full)
      await supabaseServer
        .from('queue_tickets')
        .update({ status: 'no_show' })
        .eq('id', ticket_id);

      return res.status(400).json({ 
        error: 'Doctor quota exceeded',
        message: 'Kuota dokter untuk hari ini sudah penuh',
        quota_status: 'full'
      });
    }

    // ============================================
    // Step 4: INSERT new visit record
    // ============================================
    
    const { data: newVisit, error: insertError } = await supabaseServer
      .from('visits')
      .insert({
        patient_id: patient_id,
        poli_id: poli_id,
        dokter_id: dokter_id,
        penjamin_id: penjamin_id,
        keluhan: keluhan,
        harga: harga || 0,
        kunjungan_ke: kunjungan_ke || 1,
        queue_ticket_id: ticket_id,
        status: 'pending', // Visit status: pending -> processed -> completed/selesai
        registered_at: new Date().toISOString(),
        // no_reg will be auto-generated by trigger
      })
      .select(`
        *,
        patients!inner(id, nrm, nama, jenis_kelamin),
        poli(id, nama),
        doctors(id, user_id),
        penjamin:penjamin_id(id, nama)
      `)
      .single();

    if (insertError) {
      console.error('Error creating visit:', insertError);
      throw insertError;
    }

    // ============================================
    // Step 5: Update queue ticket to completed
    // ============================================
    
    const { error: updateTicketError } = await supabaseServer
      .from('queue_tickets')
      .update({ 
        status: 'completed',
        completed_at: new Date().toISOString()
      })
      .eq('id', ticket_id);

    if (updateTicketError) {
      console.error('Error updating ticket status:', updateTicketError);
      // Don't throw - visit already created
    }

    // ============================================
    // Step 6: Get doctor name
    // ============================================
    
    let doctorName = '-';
    if (newVisit.doctors?.user_id) {
      const { data: userData } = await supabaseServer
        .from('users')
        .select('nama')
        .eq('id', newVisit.doctors.user_id)
        .single();
      
      if (userData) {
        doctorName = userData.nama;
      }
    }

    // ============================================
    // Step 7: Return success response
    // ============================================
    
    return res.status(200).json({
      success: true,
      visit: {
        id: newVisit.id,
        no_reg: newVisit.no_reg,
        patient: {
          id: newVisit.patients.id,
          nrm: newVisit.patients.nrm,
          nama: newVisit.patients.nama,
        },
        poli: {
          id: newVisit.poli?.id,
          nama: newVisit.poli?.nama,
        },
        doctor: {
          id: newVisit.doctors?.id,
          nama: doctorName,
        },
        penjamin: {
          id: newVisit.penjamin?.id,
          nama: newVisit.penjamin?.nama,
        },
        keluhan: newVisit.keluhan,
        harga: newVisit.harga,
        kunjungan_ke: newVisit.kunjungan_ke,
        registered_at: newVisit.registered_at,
      },
      message: 'Registrasi berhasil',
    });

  } catch (error: any) {
    console.error('Error in register-patient:', error);
    return res.status(500).json({
      error: 'Failed to register patient',
      message: error?.message || 'Unknown error',
    });
  }
}
